# Principal Component Analysis (PCA)

## Importing the libraries

In [1]:
import numpy as np;
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Wine.csv')

In [3]:
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [6]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


# Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [8]:
X_train

array([[1.371e+01, 1.860e+00, 2.360e+00, ..., 1.110e+00, 4.000e+00,
        1.035e+03],
       [1.222e+01, 1.290e+00, 1.940e+00, ..., 8.600e-01, 3.020e+00,
        3.120e+02],
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       ...,
       [1.242e+01, 1.610e+00, 2.190e+00, ..., 1.060e+00, 2.960e+00,
        3.450e+02],
       [1.390e+01, 1.680e+00, 2.120e+00, ..., 9.100e-01, 3.330e+00,
        9.850e+02],
       [1.416e+01, 2.510e+00, 2.480e+00, ..., 6.200e-01, 1.710e+00,
        6.600e+02]])

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 0.91083058, -0.46259897, -0.01142613, ...,  0.65706596,
         1.94354495,  0.93700997],
       [-0.95609928, -0.96608672, -1.53725357, ..., -0.40859506,
         0.58118003, -1.41336684],
       [ 0.35952243,  1.67501572, -0.37471838, ..., -1.55950896,
        -1.44846566,  0.28683658],
       ...,
       [-0.70550467, -0.68342693, -0.62902295, ...,  0.44393375,
         0.49776993, -1.30608823],
       [ 1.14889546, -0.6215951 , -0.88332752, ..., -0.19546286,
         1.0121322 ,  0.77446662],
       [ 1.47466845,  0.11155374,  0.42452457, ..., -1.43162964,
        -1.23994042, -0.28206514]])

## Applying PCA

In [11]:
# Step 3: Fit the PCA model
from sklearn.decomposition import PCA
pca = PCA()
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [12]:
# Access eigenvalues and eigenvectors
eigenvalues = pca.explained_variance_
eigenvectors = pca.components_

# Display the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[4.8923083  2.46635032 1.42809973 1.01233462 0.84906459 0.60181514
 0.52251546 0.33051429 0.29595018 0.2399553  0.21432212 0.16831254
 0.08414846]

Eigenvectors:
[[ 1.46698114e-01 -2.42245536e-01 -2.99344215e-02 -2.55190023e-01
   1.20797723e-01  3.89344551e-01  4.23264856e-01 -3.06349555e-01
   3.05722194e-01 -9.86919131e-02  3.00325353e-01  3.68211538e-01
   2.92597130e-01]
 [-5.04170789e-01 -2.42168894e-01 -2.86984836e-01  6.46871827e-02
  -2.29953850e-01 -9.36399132e-02 -1.08862204e-02 -1.87021637e-02
  -3.04035180e-02 -5.45270809e-01  2.79243218e-01  1.74365000e-01
  -3.63154608e-01]
 [ 1.17235150e-01 -1.49946576e-01 -6.56394387e-01 -5.84282337e-01
  -8.22627466e-02 -1.80804417e-01 -1.42959330e-01 -1.72234753e-01
  -1.58362102e-01  1.42421708e-01 -9.32387182e-02 -1.96077407e-01
   9.73171134e-02]
 [-2.06254611e-01 -1.30489298e-01 -1.51536318e-02  9.04220851e-02
   8.39128346e-01 -1.93179478e-01 -1.40459548e-01 -3.37332618e-01
   1.14752900e-01 -7.87857057e-02 -2.41740

In [13]:
# Access covariance matrix
covariance_matrix = pca.get_covariance()

# Display the results
print("\nCovariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[ 1.00813008  0.08797701  0.23066952 -0.32868099  0.2141631   0.35576761
   0.2991246  -0.16913744  0.09649074  0.56962271 -0.04781543  0.07403492
   0.63277882]
 [ 0.08797701  1.00813008  0.2016416   0.30658143 -0.06030917 -0.30124242
  -0.41221162  0.36616593 -0.19190146  0.30749173 -0.54992807 -0.39352761
  -0.20253906]
 [ 0.23066952  0.2016416   1.00813008  0.44971971  0.18321413  0.12235533
   0.06130256  0.18655693 -0.02607834  0.24555355 -0.10928021 -0.01820002
   0.15948032]
 [-0.32868099  0.30658143  0.44971971  1.00813008 -0.08930998 -0.37018442
  -0.41804463  0.40212108 -0.25765667 -0.03090225 -0.25313262 -0.28934372
  -0.48504311]
 [ 0.2141631  -0.06030917  0.18321413 -0.08930998  1.00813008  0.16513295
   0.14458703 -0.30763563  0.27228619  0.1260674   0.05792599  0.01596134
   0.31461066]
 [ 0.35576761 -0.30124242  0.12235533 -0.37018442  0.16513295  1.00813008
   0.88119961 -0.45396901  0.6196806  -0.06935051  0.45718802  0.72214462
   0.56326772]
 [

In [14]:
# Calculate cumulative percentage of explained variance
cumulative_explained_variance = np.cumsum(pca.explained_variance_ratio_)

# Display the results
print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)

print("\nCumulative Explained Variance:")
print(cumulative_explained_variance)


Explained Variance Ratio:
[0.37329648 0.18818926 0.10896791 0.07724389 0.06478595 0.04592014
 0.03986936 0.02521914 0.02258181 0.01830924 0.01635336 0.01284271
 0.00642076]

Cumulative Explained Variance:
[0.37329648 0.56148574 0.67045365 0.74769754 0.81248349 0.85840362
 0.89827298 0.92349212 0.94607393 0.96438317 0.98073654 0.99357924
 1.        ]


In [15]:
# Find the number of principal components that explain 95% of the variance
num_components_95_percent = np.argmax(cumulative_explained_variance >= 0.95) + 1

# Display the results
print(f"\nNumber of Principal Components for 95% Variance: {num_components_95_percent}")


Number of Principal Components for 95% Variance: 10


In [16]:
# Step 3: Fit the PCA model
from sklearn.decomposition import PCA

num_components = 2 #Choose 2 because equavalant to 50%
pca = PCA(n_components = num_components)
X_train_pca1 = pca.fit_transform(X_train)
X_test_pca1 = pca.transform(X_test)

In [17]:
X_train_pca1

array([[ 2.59891628, -0.00484089],
       [ 0.15819134,  2.26659577],
       [-2.6372337 , -2.66488569],
       [-2.52848449, -0.51846618],
       [ 1.70922581,  0.91719459],
       [-2.83057003, -0.41936129],
       [-2.82251879, -1.99763147],
       [ 1.36618015, -0.04639099],
       [-2.46584868,  0.07932269],
       [-2.28554906,  0.40096658],
       [ 1.14246632,  2.39587633],
       [-2.28497881,  1.09274988],
       [-2.52924945, -0.6477328 ],
       [ 0.169245  ,  1.1264982 ],
       [ 2.53088166, -1.05798498],
       [-0.71596964,  2.80365836],
       [ 2.46922033,  0.15871191],
       [-0.58044574,  0.69290749],
       [ 0.54583852, -0.41042188],
       [ 3.5604963 , -1.42561284],
       [ 1.58679826,  1.51260121],
       [ 2.54872139,  0.05280515],
       [-3.59338727, -0.88321901],
       [-1.60406659, -2.40373662],
       [ 1.48668426,  1.40863724],
       [ 0.00830468,  2.04898307],
       [-0.15646658,  2.80278355],
       [-2.39863877, -2.47524175],
       [-3.13549157,

In [18]:
# Step 7: Train logistic regression model on the transformed data
from sklearn.linear_model import LogisticRegression
logistic_reg_model = LogisticRegression()
logistic_reg_model.fit(X_train_pca1, y_train)

LogisticRegression()

In [19]:
# Step 8: Predict and evaluate the model
from sklearn.metrics import accuracy_score
y_pred = logistic_reg_model.predict(X_test_pca1)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.98
